# Generated by Django 4.1.1 on 2022-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.CharField(default='No photo', max_length=500, verbose_name='Изображение'),
        ),
    ]
